name: Semantic Versioning
on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Create artifact directory
        run: mkdir -p ./site

      - name: Build npm project
        run: |
          npm install
          npm run build

      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     